# Generated by Django 4.0.4 on 2022-05-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='bio',
            new_name='cat_name',
        ),
    ]
