# Generated by Django 3.2.5 on 2022-06-01 04:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_bio_usermodel_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='follower',
            field=models.ManyToManyField(related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
    ]
